name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t rust-websocket-server .
          docker tag rust-websocket-server:latest ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest
          docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest

      - name: Replace placeholders in ECS task definition
        run: |
          sed -i 's|PLACEHOLDER_FAMILY|${{ secrets.AWS_TASK_FAMILY }}|' ecs-task-definition.json
          sed -i 's|PLACEHOLDER_CONTAINER_NAME|${{ secrets.AWS_CONTAINER_NAME }}' ecs-task-definition.json
          sed -i 's|PLACEHOLDER_IMAGE|${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest|' ecs-task-definition.json
          sed -i 's|PLACEHOLDER_ACCOUNT_ID|${{ secrets.AWS_ACCOUNT }}|' ecs-task-definition.json 

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: your-ecs-service-name
          cluster: your-ecs-cluster-name
          wait-for-service-stability: true
