name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t rust-websocket-server .
          docker tag rust-websocket-server:latest ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest
          docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest

      - name: Replace placeholders in ECS task definition
        run: |
          sed -i 's|PLACEHOLDER_FAMILY|${{ secrets.AWS_TASK_FAMILY }}|' ecs-task-definition.json
          sed -i 's|PLACEHOLDER_CONTAINER_NAME|${{ secrets.AWS_CONTAINER_NAME }}|' ecs-task-definition.json
          sed -i 's|PLACEHOLDER_IMAGE|${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest|' ecs-task-definition.json
          sed -i 's|PLACEHOLDER_ACCOUNT_ID|${{ secrets.AWS_ACCOUNT }}|' ecs-task-definition.json
          sed -i 's}PLACEHOLDER_CLUSTER_NAME|${{ secrets.AWS_CLUSTER_NAME }}|' cloud-formation.yml
          sed -i 's|PLACEHOLDER_TASK_FAMILY|${{ secrets.AWS_TASK_FAMILY }}|' cloud-formation.yml
          sed -i 's|PLACEHOLDER_CONTAINER_NAME|${{ secrets.AWS_CONTAINER_NAME }}|' cloud-formation.yml
          sed -i 's|PLACEHOLDER_ACCOUNT_ID|${{ secrets.AWS_ACCOUNT }}|' cloud-formation.yml
          sed -i 's|PLACEHOLDER_REGION|${{ secrets.AWS_REGION }}|' cloud-formation.yml

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: ${{ secrets.AWS_SERVICE_NAME }}
          cluster: ${{ secrets.AWS_CLUSTER_NAME }}
          wait-for-service-stability: true

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloud-formation.yml \
            --stack-name rust-websocket-server-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              ImageUri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/rust-websocket-server:latest \
            --region ${{ secrets.AWS_REGION }}
